### ISSUE TITLE
sourcesChanged doesn't update UI

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#103]
## Issue
When I use the `sourcesChanged()`, the DSE UI doesn't show the updates. On the other hand, if I use the other `_Changed()` methods, it does.

## How to reproduce
1. Make a simple DS file with a `weight` axis, at least 1 source, and at least one instance.
2. Run this script:

```python
d = CurrentDesignspace()   

# Updates in UI
d.instances[0].location["weight"] = 15
d.instancesChanged()

# Doesn't update in UI
d.sources[0].location["weight"] = 15
d.sourcesChanged()
```

**Comment by typemytype** [comment]
should be fixed

**Comment by ryanbugden** [comment]
Thanks! I think this fixed a bit, but noticed some other issues with notifications here: https://github.com/LettError/designSpaceRoboFontExtension/issues/104
