### ISSUE TITLE
Some UI elements not updating with scripts

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#104]
## Issue
Some UI elements do not update visually, even when `_Changed()` notifications are sent.

## To reproduce
Click New Designspace, and then run [this script](https://gist.github.com/ryanbugden/99e86710646aeed94a710d77ca329e33). 
> Note: this tests only some attributes of some descriptors; it's not exhaustive. Results are detailed below.

### Axes
> Note: Adding Descriptors doesn't seem to need a "changed" notification in order to be reflected in the UI.

**Name**
✅ Adding
✅ Updating

**Tag**
✅ Adding
✅ Updating

**Axis Labels**
✅ Adding
✅  Updating

### Sources
**Style Name**
✅ Adding
✅ Updating

**Location**
❌ Adding
❌ Updating

### Instances
**UFO Path**
✅ Adding
❌ Updating

**Style Name**
✅ Adding
✅ Updating

### Rules, Location Labels, & Variable Fonts
❌ Adding
❌ Updating

**Comment by typemytype** [comment]
cool! thanks for the testing suite!! I made some comments in the gist

I pushed some changes to the DS extension (84ca39caca8f9aee7fb525e240c473ae65ebeac0) 

This needs a fresh RF build to get the improved ufoProcessor

**Comment by ryanbugden** [comment]
Thanks Frederik!
