### ISSUE TITLE
Axis Without On-Axis Sources

### ISSUE THREAD

**Issue by sponcey** [LettError/designSpaceRoboFontExtension#12]
I'm getting this error in the design space editor:

<img width="791" alt="Screen Shot 2019-05-02 at 5 22 10 PM" src="https://user-images.githubusercontent.com/29526738/57108006-8bd58f80-6cff-11e9-93ec-4f6d4bb3dbac.png">

Here are my axes:

<img width="816" alt="Screen Shot 2019-05-02 at 5 22 18 PM" src="https://user-images.githubusercontent.com/29526738/57108038-a27be680-6cff-11e9-8925-a638724fc4a5.png">

And my masters:

<img width="893" alt="Screen Shot 2019-05-02 at 5 22 35 PM" src="https://user-images.githubusercontent.com/29526738/57108055-aad42180-6cff-11e9-8f87-d06224872675.png">

I tried adding a 4th master (weight min) but that did not fix the problem. Why am I getting this error message?

**Comment by LettError** [comment]
Hi @sponcey, thanks for the report. When I construct a designspace with this geometry, with the current version of DSE, I don't get this problem. Could you check with the 1.6.8 version (through Mechanic, or from [here](https://github.com/LettError/designSpaceRoboFontExtension) and see if you still get the same problem?

**Comment by LettError** [comment]
Updated the designspaceProblems.

**Comment by sponcey** [comment]
I updated and I'm not getting this error anymore! Thanks :)

**Comment by LettError** [comment]
Thanks!
