### ISSUE TITLE
Incorrect check when axis <map> exists: "source location has out of bounds location"

### ISSUE THREAD

**Issue by thundernixon** [LettError/designSpaceRoboFontExtension#15]
If a designspace has an axis map, Designspace Editor will tend to incorrectly report source axis locations as "out of bounds." 

In a designspace file, source locations weights must relate to the "master values," as described in the `output` weights of the `map`. However, the `checkSources()` function is seemingly comparing them to the axis `minimum` and `maximum` values without considering the `map` values.

https://github.com/LettError/designSpaceRoboFontExtension/blob/29b848978ca4cc545359d1c981a62ab0f2bb49f6/DesignSpaceEditor.roboFontExt/lib/designspaceProblems/__init__.py#L222-L225

As a simple example of this, here's a zip of Fira Code, with two master OTFs and a designspace:

[master_ufo.zip](https://github.com/LettError/designSpaceRoboFontExtension/files/3493222/master_ufo.zip)

```xml
<axes>
    <axis tag="wght" name="Weight" minimum="300" maximum="700" default="300">
      <map input="300" output="62"/>
      <map input="400" output="84"/>
      <map input="450" output="96"/>
      <map input="500" output="112"/>
      <map input="700" output="158"/>
    </axis>
  </axes>
  <sources>
    <source filename="FiraCode-Light.ufo" name="Fira Code Light" familyname="Fira Code" stylename="Light">
      <lib copy="1"/>
      <groups copy="1"/>
      <features copy="1"/>
      <info copy="1"/>
      <location>
        <dimension name="Weight" xvalue="62"/>
      </location>
    </source>
    <source filename="FiraCode-Bold.ufo" name="Fira Code Bold" familyname="Fira Code" stylename="Bold">
      <location>
        <dimension name="Weight" xvalue="158"/>
      </location>
    </source>
  </sources>
```

This designspace is generated by FontMake from a Glyphs file with the command `fontmake -g FiraCode.glyphs -o variable`. Here's a repo, if helpful: https://github.com/thundernixon/FiraCode/tree/qa

Here's the Problems report that results:

![image](https://user-images.githubusercontent.com/7355414/62876867-dfd71380-bcf3-11e9-8183-51907735f685.png)

As the axis map is one of the harder things for beginners to grasp in the designspace spec, this would be a handy thing to update in the designspace checker.

**Comment by thundernixon** [comment]
Just to add to this: a seemingly-related issue exists in Skateboard.

If I try to open a designspace that has a source with a lighter weight value than my declared axis range, it fails to open:

```
Traceback (most recent call last):
  File "/var/folders/bk/sprf07508xjg9100r6_j2qch0000gp/T/tmpxw0clx1q/lib/skateboard.py", line 5116, in _openDesignspaceDocument
  File "/var/folders/bk/sprf07508xjg9100r6_j2qch0000gp/T/tmpxw0clx1q/lib/skateboard.py", line 3016, in document_checkAxes
  File "/Applications/RoboFont3.3b.app/Contents/Resources/lib/python3.6/ufoProcessor/varModels.py", line 20, in __init__
  File "/Applications/RoboFont3.3b.app/Contents/Resources/lib/python3.6/ufoProcessor/varModels.py", line 38, in _makeWarpFromList
  File "/Applications/RoboFont3.3b.app/Contents/Resources/lib/python3.6/fontTools/varLib/models.py", line 197, in __init__
ValueError: locations must be unique
```

However, this type of weight value works perfectly fine to build a variable font via FontMake.

Here's a permalink to a designspace that is failing to open in Skateboard for this reason: https://github.com/arrowtype/recursive/blob/0c897e9c64bc3f6cf71f20f6f3ee6d5d8b3961f4/src/masters/sans/Recursive-sans--xprn_wght_slnt_ital.designspace

I have a weight map like this:

```
<axis tag="wght" name="Weight" minimum="300" maximum="900" default="300">
      <labelname xml:lang="en">Weight</labelname>
      <map input="300" output="250" />
      <map input="400" output="350" />
      <map input="500" output="500" />
      <map input="600" output="600" />
      <map input="700" output="700" />
      <map input="800" output="800" />
      <map input="900" output="900" />
</axis>
```

...and sources like this:

```
<source filename="Recursive Sans-Casual A Slanted.ufo" familyname="Recursive Sans" stylename="Casual A Slanted">
      <location>
        <dimension name="Weight" xvalue="250" />
        <dimension name="Slant" xvalue="-15" />
        <dimension name="Italic" xvalue="0.500000" />
        <dimension name="Expression" xvalue="1" />
      </location>
</source>
```

If I simply edit the source's Weight `xvalue` to `300`, and adjust the axis's default to `800` (so it's on a master), then it opens in Skateboard. However, this (probably) shouldn't be necessary to do.

**Comment by LettError** [comment]
Note to self: https://github.com/fonttools/fonttools/issues/1655

**Comment by LettError** [comment]
Note to self, WIP
* changes to tests in designspaceProblems https://github.com/LettError/DesignspaceProblems/tree/user-designspace-mapping
* new axismapper https://github.com/LettError/ufoProcessor/tree/user-designspace-mapping

**Comment by typemytype** [comment]
closing this in favor of https://github.com/LettError/designSpaceRoboFontExtension/tree/dse2.0
