### ISSUE TITLE
Should ufoProcessor be embedded in designSpaceRFE as a module?

### ISSUE THREAD

**Issue by jbmorizot** [LettError/designSpaceRoboFontExtension#17]
Maybe it would make the extension too big… so maybe just the parts needed?

**Comment by LettError** [comment]
Have you tried installing ufoProcessor as a separate package for Robofont?
https://forum.robofont.com/topic/708/how-to-run-skateboard-on-rf3-3b-build-1906031450

**Comment by jbmorizot** [comment]
Yes, it works, perfect, thanks!
