### ISSUE TITLE
UI bugs on opening

### ISSUE THREAD

**Issue by agyeiarcher** [LettError/designSpaceRoboFontExtension#18]
I have an issue with my designspace file, where opening it gives me this:
<img width="915" alt="Screenshot 2020-03-18 at 11 15 40 PM" src="https://user-images.githubusercontent.com/34943654/77028280-bd366880-696e-11ea-8cca-82b71aca58b0.png">

The thing about this is that when I revisit the Axes tab after opening another, it's fine, but sometimes, my axis labels and values are missing. (pardon my incorrect labelling tags)

<img width="1231" alt="Screenshot 2020-03-18 at 11 14 39 PM" src="https://user-images.githubusercontent.com/34943654/77028395-ff5faa00-696e-11ea-82cf-2f918ce054d8.png">

But if I delete some source masters, I can see the values again, but no labels

<img width="1229" alt="Screenshot 2020-03-18 at 11 15 01 PM" src="https://user-images.githubusercontent.com/34943654/77028413-0dadc600-696f-11ea-9567-f2c425be9c38.png">

I'm pretty sure there's something I'm not doing right in the handling of the files, any ideas?

**Comment by LettError** [comment]
Thanks for the report! Sorry I missed it when you posted it. Does the issue still happen? Could you share the data so I can test?

**Comment by typemytype** [comment]
@agyeiarcher can you share the erroneous designspace file? 
or close this issue, thanks

**Comment by typemytype** [comment]
closing due no answers given... and probably fixed in the new DS5 https://github.com/LettError/designSpaceRoboFontExtension/tree/dse2.0
