### ISSUE TITLE
Missing Attribute settingsIdentifier

### ISSUE THREAD

**Issue by michielkauwatjoe** [LettError/designSpaceRoboFontExtension#2]
When trying to create a new design space:

```
Traceback (most recent call last):
  File "newDesignSpaceFile.py", line 3, in <module>
  File "/Users/michiel/source/git/designSpaceRoboFontExtension/DesignSpaceEditor.roboFontExt/lib/window.py", line 485, in __init__
AttributeError: 'module' object has no attribute 'settingsIdentifier'
```

**Comment by LettError** [comment]
That is odd, it's defined in settings.py.

**Comment by michielkauwatjoe** [comment]
Oh by the way, this is on Sierra with the latest build from source of RoboFont...

**Comment by LettError** [comment]
I can not recreate either of those conditions :) Could you see if it is maybe addressing the right settings.py? Which file for instance?

**Comment by michielkauwatjoe** [comment]
It seems to be pointing directly to the sources folder from git (which contains a settings.py file). I've installed it simply by doubleclicking the .ext, is there a better way?

**Comment by LettError** [comment]
You can view this in Pycharm, right? So, can you see why it is not finding the settings.settingsIdentifier ? I know "it works here" is not very helpful, but I can't recreate the problem.

**Comment by LettError** [comment]
Of bel ff :)

**Comment by michielkauwatjoe** [comment]
Zitten nu even in een meeting en moet zo weg, wat moet ik in PyCharm bekijken?

**Comment by LettError** [comment]
Of je die settings en inhoud kan vinden?

**Comment by justvanrossum** [comment]
Note that the private modules you use in an extension are not private at all. For instance, if I do "import settings" in RF I get a DrawBot-in-RF dialog: 
```
import settings
print settings.__file__
>>>
/Users/just/Library/Application Support/RoboFont/plugins/DrawBot.roboFontExt/lib/settings.py
```

So calling modules inside extensions such generic names is a recipe for confusion it seems.
Cc @typemytype

**Comment by typemytype** [comment]
oh, that is an issue that came by for other extensions. I guess its first in first out...
There is already an extension having a module settings that is being called from `import settings` and that is being set in the `sys.modules` 

I don't have an idea how to solve this, accept for using specific module naming: designSpaceSettings.py???

**Comment by justvanrossum** [comment]
Yes, modules in extensions should use their extension name as a prefix.

**Comment by LettError** [comment]
scope! Thanks @justvanrossum and @typemytype, I will make the changes.

**Comment by LettError** [comment]
Fixed.

**Comment by michielkauwatjoe** [comment]
Thanks, it works now! (By the way, there seems to be a typo in the file name `newDesignspaceFIle.py`...)
