### ISSUE TITLE
UI columns not resizable

### ISSUE THREAD

**Issue by ddaanniiieeelll** [LettError/designSpaceRoboFontExtension#22]
<img width="1503" alt="Bildschirmfoto 2021-01-08 um 12 33 49" src="https://user-images.githubusercontent.com/9609886/104011402-53fa3d00-51ae-11eb-81a3-dfaf3b6af844.png">

As you can see the Style Names are not completely readable. I expected to be able to resize the columns by clicking and dragging the bar between two columns when the ⟷ cursor appears. However this cursor does not appear and I'm only able to rearrange the order of the columns.
I can't seem to find out what it is that I'm doing wrong.

According to Mechanic2 I'm using 1.9.4b which should be the up to date one?

P.S. I know the file names are too long, but resizable columns would still be nice.

**Comment by LettError** [comment]
resizing would be nice.

**Comment by ddaanniiieeelll** [comment]
Hmm, I just took a look into the vanilla documentation. 
If I build a simple window with a list inside, the columns are resizable.
→  quick glance into the `designSpaceEditorwindow.py` shows the same structure to build the list.
Also since I couldn’t find a specific argument I’m guessing the columns are resizable by default (?).

It probably has something to do with the way the editor window is build and how the list is implemented, but my python is not yet advanced enough to find out why it is not working the way I want.

Quick and dirty solution: hardcode the columns wider 😬 🤷‍♂️

**Comment by LettError** [comment]
Thank you @ryanbugden for the PR

**Comment by rohernandezz** [comment]
Thank you @ryanbugden, you improved my week about an order of magnitude :👍🏼👍🏼👍🏼👍🏼👍🏼👍🏼

**Comment by ryanbugden** [comment]
Great to here, Romina!
