### ISSUE TITLE
"Auto-populate instance ufo file names" button

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#23]
This is a "nice-to-have", but it could be nice to not manually type all of the UFO instance output file names.

I personally always do something like this:
`instances/Family_Name-Style_Name` , `Family Name`, `Style Name` , etc.
The button would look at the latter two and auto-populate the first. At least as a starting point, this could be helpful to many people, I reckon.

I realize this will be tough to implement without putting a stake in the ground around file-naming conventions, etc., but just an idea. I will also look into it when I have time. 

Thanks for the nice extension!

**Comment by LettError** [comment]
Changes to either of the font names should then always reflect in the ufo instance name? Maybe it could be a button that updates the ufo pathnames based on the fontname fields. Then there is a choice to update or not.

**Comment by LettError** [comment]
Added. It works here, if you could verify I will update the version number.

**Comment by ryanbugden** [comment]
Nice! Updates and works when I hit the Save button. 
🙏
