### ISSUE TITLE
Respect instance filepaths in the document

### ISSUE THREAD

**Issue by LettError** [LettError/designSpaceRoboFontExtension#3]
If no changes are made to an instance, the **filename** attribute should not change when writing it back to file.

`<source familyname="MasterFamilyName" filename="../Roman/Regular/font.ufo" name="master.ufo1" stylename="MasterStyleNameOne">`

#### Case 1: Existing document, existing instance:
- on reading, store the **filename** string in the instanceDescriptor.
- calculate an absolute path relative to the document path so we can see if the file exists and access it if we have to
- use the **filename** attribute again when writing, regardless of the instance folder name from preferences.

#### Case 2: Existing document, new instance:
This is a tricky one: should it look at the existing instances and make a guess? Or follow the pattern for new instances?

#### Case 3: New document, new instance:
The instanceDescriptors have no idea of the filename or preferred path. So: create a path name out of the preferred instance folder name from the preferences + familyName + instanceName + ufo extension.
- This is what the editor does at the moment, and it does not leave any room for modifications, nor does it respect existing values.

## Expected editor behaviour:
- Show the **filename** in the **UFO** column in the Instance list.
- Make it editable, "show folder" button?
- Maybe show the absolute version of this path, or "show in Finder"?

**Comment by frankrolf** [comment]
I think even if changes are made to an instance (e.g. axis position), the pre-defined file name should not change. 

Case 1: sounds perfect
Case 2: I think in that case, it should just default to your standard naming and/or path assignment. Ideally, that path would be obvious & editable.
Case 3: Everything default. Sounds good.

The big change would be:
– keeping custom paths if they exist (very important)
– allowing to define custom paths in the Designspace Editor (nice-to-have, but less important if they stick after editing the XML)

**Comment by LettError** [comment]
https://github.com/LettError/designSpaceDocument/commit/22ce159ecd5e06be8c3b7e04b5ebac70e7fa7aae

* Custom paths are kept on read / write.
* Managing expectations is a bit complex, but most of it works.
