### ISSUE TITLE
Create a column for each axis on the fly, as opposed to empty placeholders

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#34]
Getting rid of columns we don't need, will help the earlier column-resizing ability really flex open and work nicely.

Currently trying to figure out a way to do this dynamically. Easy for me to figure out upon extension, but it's tricky trying to figure out the dependencies when adding an axis in the extension. I've started a version [here](https://github.com/ryanbugden/designSpaceRoboFontExtension/blob/c4ac64702430a1aa6b6f88ee3682ae79092b1d89/extensionLib/designSpaceEditorwindow-dynamic_columns.py#L1011). If you're interested, it could be cool to see this through, and you're obviously more familiar with how everything is set up. Mine's already broken, with the add-axis buttons not working (with no traceback); I've started adding some print statements to debug.

Linked above is my main edit. The other significant change I started is [here](https://github.com/ryanbugden/designSpaceRoboFontExtension/blob/c4ac64702430a1aa6b6f88ee3682ae79092b1d89/extensionLib/designSpaceEditorwindow-dynamic_columns.py#L1736).

Using the real estate nicely so far!
<img width="815" alt="image" src="https://user-images.githubusercontent.com/12752088/167227796-d6a43c74-8abb-4a45-8cc5-77dd455f9826.png">

**Comment by LettError** [comment]
My experiences with dynamically changing things in List aren't very good - but that's perhaps because I don't know enough about the internals. There is some deep pyobcj foo going in and I didn't want to bother Frederik or Tal. If you can get it to work though..

**Comment by typemytype** [comment]
closing this in favor of the new DS5 editor https://github.com/LettError/designSpaceRoboFontExtension/tree/dse2.0
