### ISSUE TITLE
Support for DesignSpace 5

### ISSUE THREAD

**Issue by nicksherman** [LettError/designSpaceRoboFontExtension#36]
I know the ink is barely dry on the spec for [DesignSpace 5](https://fonttools.readthedocs.io/en/latest/designspaceLib/scripting.html#working-with-designspace-version-5), but I'm looking forward to using it to replace other tools for setting STAT table info. And of course if that is possible with DesignSpaceEditor, all the better :)

I probably can't be of much help as far as technical implementation, but I'd be happy to offer UI suggestions or feedback if you'd like.

**Comment by LettError** [comment]
I expect a UI to be very complex. I'm not sure it all STAT stuff needed to be in designspace. I'm not sure I'm volunteering to engineer all this.

**Comment by nicksherman** [comment]
A very understandable position! You won’t hear any grumbles from me if you don't see this as being in the scope of DesignSpaceEditor and close this issue as `won't fix` accordingly.

**Comment by typemytype** [comment]
the new designspace editor can edit labels and preview them 

seen https://github.com/LettError/designSpaceRoboFontExtension/tree/dse2.0
