### ISSUE TITLE
[2.0] notifications

### ISSUE THREAD

**Issue by typemytype** [LettError/designSpaceRoboFontExtension#43]
- [x] `designspaceEditorWillOpenDesignspace`;: will open a designspace file
- [x] `designspaceEditorDidOpenDesignspace`: did open a designspace file
- [x] `designspaceEditorDidChange`: anything did change
- [x] `designspaceEditorLabelsDidChange`: labels did change
- [ ] `designspaceEditorWillAddSource`
- [ ] `designspaceEditorDidAddSource`

**Comment by LettError** [comment]
- [ ] `designspaceEditorSourceOpened` is sent when a UFO that is part of the current designspace is opened in RF (and now needs to use the "live" data)
- [ ] `designspaceEditorSourceClosed` is sent when a UFO that is part of the current designspace is closed in RF (and now needs to be loaded from file)
- [ ] `designspaceEditorSourceChanged` is sent when RF notices a UFO has been changed on disk *1
- [ ] `designspaceEditorCurrentLocationChanged` is sent when the current location is changed in DSE
- [ ] `designspaceEditorChangedInstances` is sent when there is a significant change in instance location, `avar` values, etc
- [ ] `designspaceEditorChangedMathModel` is sent when the math model changes

## Receiving
- [ ] `designspaceEditorUpdateCurrentLocation` is *received* when the current location is changed somewhere else, for instance in Skateboard, and we want DSE to update
- [ ] `designspaceEditorAddInterestingLocation` is *received* to store a designspace location, with name, in the designspace lib

**Comment by typesupply** [comment]
Would `designspaceEditorDidSaveDesignspace` be useful?

**Comment by LettError** [comment]
Notifications ready and working: https://letterror.github.io/designSpaceRoboFontExtension/#toc_12b
