### ISSUE TITLE
Not saving NEw or edited Designspace files.

### ISSUE THREAD

**Issue by dberlow** [LettError/designSpaceRoboFontExtension#44]
MacOS 12.6
Robofont Version 4.3 (build 2210191628)
Latest Dsignspace Edit

New, 
add axis,
save, input name
title of file remains "untitled"
save is no longer an option. 

Editing existing files also accepts edits but does not save them

I have plenty of disc space. 

This was no happening 1 week ago.

**Comment by typemytype** [comment]
Strange, dont know what is happening... are you using the old designSpace editor? or the in [progress DesignSpace v5 editor](https://github.com/LettError/designSpaceRoboFontExtension/tree/dse2.0)? 

I cannot reproduce this on my local machine with the given instructions.

**Comment by dberlow** [comment]
Thanks, I was using the old version after an update.

**Comment by typemytype** [comment]
the latest RoboFont has fontTools with designspace v5 embedded. This works only partially with the old extension.
