### ISSUE TITLE
Easier Save As folder & pre-populated name

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#46]
It might be nice if, upon `Save As`, the default save folder for the pop-up dialog was set to the folder containing the current designspace, rather than the folder containing the sources. 

And if the default name was equal to the name of the current ds file, rather than `Untitled`, so a minor change could be quickly made to the file name. 

I can make this change, but just leaving here as a note to self.

**Comment by typemytype** [comment]
a PR would be nice in the DS2.0 branch, thanks

**Comment by ryanbugden** [comment]
Done.
DSE 2 looks beautiful @LettError @typemytype
