### ISSUE TITLE
Keep track of the current preview location in DSE

### ISSUE THREAD

**Issue by LettError** [LettError/designSpaceRoboFontExtension#61]
The concept will come up when thinking about navigation and previewing. So, something needs to keep track of the location. I don't think it is the UFOOperator's responsibility, but I can be convinced otherwise. Can be stored in the designspace lib.

**Comment by typemytype** [comment]
is this handled with `getPreviewLocation()` and `setPreviewLocation()` and the associated subscriber `designspaceEditorPreviewLocationDidChange` notification?

**Comment by LettError** [comment]
Yes! Can close!
