### ISSUE TITLE
Auto-postscript font name has spaces

### ISSUE THREAD

**Issue by ryanbugden** [LettError/designSpaceRoboFontExtension#64]
https://github.com/LettError/designSpaceRoboFontExtension/blob/fa5d900ec7dedafe17dd0a8f72db2c86da460ef9/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py#L1279C69-L1279C69

I think the only characters allowed are:
`!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{|}~`

If I'm reading the [spec](https://learn.microsoft.com/en-us/typography/opentype/spec/name) correctly:
> PostScript name for the font; Name ID 6 specifies a string which is used to invoke a PostScript language font that corresponds to this OpenType font. When translated to ASCII, the name string must be no longer than 63 characters and restricted to the printable ASCII subset, codes 33 to 126, except for the 10 characters '[', ']', '(', ')', '{', '}', '<', '>', '/', '%'.

**Comment by LettError** [comment]
Yikes I knew that. Will fix.
