### ISSUE TITLE
[locationPreview] new duplicated instance remains connected to original

### ISSUE THREAD

**Issue by LettError** [LettError/designSpaceRoboFontExtension#69]
Select instance / click "Duplicate" / change one of the axis values -> observe the value in the original instance change as well.

**Comment by typemytype** [comment]
oh

`instance.asdict()` does not do a deep copy of fe locations... so the object is for location is the same

will fix it

**Comment by typemytype** [comment]
```python
d = CurrentDesignspace()

i = d.instances[-1]

c = i.asdict()

print(id(i.designLocation))
print(id(c["designLocation"]))
```
