### ISSUE TITLE
Sources panel, show default indicator for each continuous space

### ISSUE THREAD

**Issue by LettError** [LettError/designSpaceRoboFontExtension#70]
If there are discrete axes there will be more default fonts. The blue diamond should be shown for each.

**Comment by typemytype** [comment]
mmm we started something, probably never finished... should there be a different mark for a discrete default and a default for the whole designspace? 

https://github.com/LettError/designSpaceRoboFontExtension/blob/master/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py#L59-L60

**Comment by LettError** [comment]
How important is the default value of a discrete axis?

**Comment by typemytype** [comment]
the default of all defaults is not really important! so maybe we should keep it like you committed
