### ISSUE TITLE
Designspace is often camelCased in documentation

### ISSUE THREAD

**Issue by roberto-arista** [LettError/designSpaceRoboFontExtension#75]
![Screenshot 2023-12-13 at 21 09 32](https://github.com/LettError/designSpaceRoboFontExtension/assets/2218712/b74c5657-6460-47af-8216-5ed79ff25ffe)

**Comment by LettError** [comment]
My apologies. I was unsupervised for some time.

**Comment by roberto-arista** [comment]
I'll take care tomorrow : )

**Comment by roberto-arista** [comment]
@LettError should I edit the index.html file directly, or it is compiled from another source?

**Comment by roberto-arista** [comment]
I refer to this file: https://github.com/LettError/designSpaceRoboFontExtension/blob/master/DesignspaceEditor2.roboFontExt/html/index.html

**Comment by LettError** [comment]
Edit the html there.
