### ISSUE TITLE
designspace format version number problem

### ISSUE THREAD

**Issue by andyclymer** [LettError/designSpaceRoboFontExtension#8]
I'm having a problem with a change that the DesignSpaceEditor makes to a .designspace file's `designspace format` string. I can't quite figure out where this problem is happening, but here's what I observe —

- I export a .designspace document out of Superpolator, and the `designspace format` version is `"3"`
- I open the file in the DesignSpaceEditor, make some changes, and save the updated file. The `designspace format` version has changed to `"4.0"`
- When I then use this .designspace file in RoboFont's Batch extension to generate a variable font, the format version trips up this line in the DesignSpaceDocument:
https://github.com/LettError/designSpaceDocument/blob/master/Lib/designSpaceDocument/__init__.py#L561

Should the DesignSpaceDocument be updated to accept a float for the version number string? 

Or should the DesignSpaceEditor be fixed to save it as an integer in a string? I can't quite figure out where I would make this change to the editor.

**Comment by anthrotype** [comment]
https://github.com/LettError/designSpaceDocument has been moved to `fontTools.designspaceLib`. You should not use the former any more, change your extension to use the latter instead, it provides the same API.
