### ISSUE TITLE
Source can no longer be added or removed

### ISSUE THREAD

**Issue by dberlow** [LettError/designSpaceRoboFontExtension#80]
The option is gone.
<img width="1209" alt="image" src="https://github.com/LettError/designSpaceRoboFontExtension/assets/1956494/2699cff3-cfa2-4c16-8440-e68a0e1e3aa5">

Mac OS Ventura 13.6.3
Robofont Version 4.3 (build 2210191628)

**Comment by LettError** [comment]
The Designspace Editor has a completely new version: DSE2. Please update if you can.
Available from Mechanic2, or here https://github.com/LettError/designSpaceRoboFontExtension.
Documentation: https://letterror.github.io/designSpaceRoboFontExtension/

**Comment by dberlow** [comment]
Thanks. Your advise proceeds via Mechanic saying 4.4? must be installed, but then trying to install from there is an error unless 4.5b is installed?
<img width="296" alt="Screenshot 2024-01-08 at 7 52 23 AM" src="https://github.com/LettError/designSpaceRoboFontExtension/assets/1956494/af1d5acf-45ef-4588-b66c-36451300e899">

**Comment by LettError** [comment]
Ah yes I guess it is RF 4.5b. Would it be possible to use the beta?

**Comment by dberlow** [comment]
Thanks. I'd like to use it, but am mid-product alpha, I was using 4.3, and
am just reading through the version history of the betas to prepare for a
discussion with my co-workers.

**Comment by LettError** [comment]
Ok. DSE2 supports almost all of the current Designspace 5 format. For that we needed to rewrite most of the plumbing. That is what became UFOOperator. DSE2 also sends a series of new notifications to support scripting in and around designspaces. All of which necessitated an update of RF itself.
[This video shows the interesting bits of DS5, DSE2, RF4.5, UFOOperator.](https://robofont.com/events/robohackathon-ds5/)
