### ISSUE TITLE
Installation issue: Requiring 4.5b

### ISSUE THREAD

**Issue by micahmicah** [LettError/designSpaceRoboFontExtension#83]
<img width="712" alt="Screenshot 2024-02-08 at 11 54 01 AM" src="https://github.com/LettError/designSpaceRoboFontExtension/assets/1166088/2edceb68-1d2f-41c4-95b6-544d1bfc5f37">

When attempting to install through Mechanic 2 I'm receiving an error that states I need RF 4.5b. 

Currently I'm not seeing the ability to download 4.5b on the [Robofont site](https://www.robofont.com/downloads/)

**Comment by LettError** [comment]
Aha! If you have access to the RoboFont server on Discord, there is a channel that posts all the download links and change reports.

**Comment by micahmicah** [comment]
Ah great! I’ve been out of it for a bit so I keep forgetting the action is happening on the Discord :)
