### ISSUE TITLE
Wrong language code reference

### ISSUE THREAD

**Issue by justvanrossum** [LettError/designSpaceRoboFontExtension#84]
The "Axis Label editor syntax" documentation links to https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags.

However, the codes needed for .designspace are IETF BCP 47 language tags (https://en.wikipedia.org/wiki/IETF_language_tag), as used in HTML and XML.

For example, for French we need 'fr' (as the examples correctly show), but the OpenType page shows `fra`, which would not be correct in the .designspace (XML) context. Perhaps it's better to link to that IETF Wikipedia page?

**Comment by typemytype** [comment]
changed! thanks for the notice
