### ISSUE TITLE
Clarify in the docs that rules are not executed in the Preview window

### ISSUE THREAD

**Issue by typemytype** [LettError/designSpaceRoboFontExtension#86]
see several threads on the RF discord:

https://discord.com/channels/1052516637489766411/1211435153960738816
https://discord.com/channels/1052516637489766411/1210425006014603305

**Comment by LettError** [comment]
Now the docs read """The rules tab is an editor for defining rules and condition sets. Tools may interpret these rules into rvrn features. The [Preview Window](https://letterror.github.io/designSpaceRoboFontExtension/#location-preview-window) does not show the rules in action. While this would indeed be useful, it requires compiling the features and that is currently outside the scope of this extension. We recommend using FontGoggles for proofing the rules."""
