### ISSUE TITLE
No "Make Default" Button

### ISSUE THREAD

**Issue by dberlow** [LettError/designSpaceRoboFontExtension#9]
I'm trying this neat tool out, but I can't find a way to define the Default font. There is clear documentation, but no "Make Default" button I can see.

<img width="940" alt="screen shot 2018-08-21 at 7 07 10 am" src="https://user-images.githubusercontent.com/1956494/44398183-fc8da080-a510-11e8-8415-0ce91ef73557.png">

Thanks.

**Comment by LettError** [comment]
Documentation needs to be updated. The default is now defined as the master that sits on the default value of each axis. So there is no need to designate one master as the default.

**Comment by dberlow** [comment]
Thanks so much for your help. Great tool!

On Aug 21, 2018, at 5:13 PM, Erik van Blokland <notifications@github.com> wrote:

Documentation needs to be updated. The default is now defined as the master that sits on the default value of each axis. So there is no need to designate one master as the default.

**Comment by campbellgraphics** [comment]
Sorry, I still don't get it. In David's example, the regular weight UFO has the default value set for the 3 axes, yet he's still getting the "can't generate...do default font" message. (I'm in the same situation). thanks

**Comment by LettError** [comment]
Hi @campbellgraphics, I posted a [small update](https://github.com/LettError/designSpaceRoboFontExtension).  I don't have test data that recreate this particular problem, but found some other things. If you're on RF3.1 you could give it a shot. Otherwise if you have a small test that can be shared off-list I will look at that.

**Comment by campbellgraphics** [comment]
Thanks, Erik. Meanwhile I fond that the same file that wasn't working correctly did work correctly once I closed and reopened it, so it must have been a minor fluke.

**Comment by LettError** [comment]
Ok thanks.
