### ISSUE TITLE
Changing Instance Path causes it to appear in Designspace Problems

### ISSUE THREAD

**Issue by colinmford** [LettError/designSpaceRoboFontExtension#98]
I will try to fix this when I get a minute but the steps to reproduce:

1. Open a properly formed and valid Designspace document, with instances
2. Go to Problems tab, run "Check for Problems", there should be no "Missing Output Path" error for instances
3. Go to Instances tab, use the "update ufo file name" menu item, even if it does not change
4. Go back to Problems tab and click "Check for Problems", there will be a new "Missing Output Path" error for the instance that was touched, even though the path does exist
5. Save, Close and Reopen Designspace
6. Run "Check for Problems", there should be no "Missing Output Path" error for instances again

Strange!

Recording: https://capture.dropbox.com/Rh5FM38CjLaM4T9Y

**Comment by typemytype** [comment]
seems like `# wrapInstanceDescriptor will create a new default filename` does not recreate a new default name
https://github.com/LettError/designSpaceRoboFontExtension/blob/master/DesignspaceEditor2.roboFontExt/lib/designspaceEditor/ui.py#L1699

**Comment by typemytype** [comment]
should be fixed, could you test before I touch the version number? 

thanks!

**Comment by colinmford** [comment]
@typemytype Works! Thanks!
