### ISSUE TITLE
Proposal: Number fields in preview location pop-over

### ISSUE THREAD

**Issue by colinmford** [LettError/designSpaceRoboFontExtension#99]
It would be helpful to have number fields attached to these sliders so you could type out a specific location if you wanted to.

<img width="340" alt="image" src="https://github.com/user-attachments/assets/1190903b-31b9-4c89-be27-68afcd7b8799">

Something similar to FontGoggles:

<img width="295" alt="image" src="https://github.com/user-attachments/assets/f9ab0220-e8cc-453c-ad11-43073fb0caba">

**Comment by typemytype** [comment]
added: 
<img width="419" alt="image" src="https://github.com/user-attachments/assets/ba71b57a-74c4-4b5a-90fe-cc3d8f8003bd">

**Comment by colinmford** [comment]
Wow, literally a 4 character commit. EZUI is amazing :)

**Comment by typemytype** [comment]
Ezui is the best!

@typesupply

**Comment by colinmford** [comment]
@typemytype I tested it, it works for me! I'll close this.
